async function lorem() {
    const sentences = [
        'do eiusmod tempor incididunt ut labore et dolore magna aliqua Utenim ad minim veniam quis nostrud exercitation ullamco laboris nisiut aliquip ex ea commodo consequat Duis aute irure dolor inreprehenderit in voluptate velit essecillum dolore eu fugiat nullapariatur Excepteur sint occaecat cupidatat non proident sunt inculpa qui officia deserunt mollit anim id est laborum Lorem ipsumdolor sit amet consectetur adipiscing elit sed incididunt ipsum Utidpariatur ut sint tempor amet sunt velit ut consectetur animdolore Excepteur', 
        'elit sed do eiusmod tempor incididunt ut labore et dolore magnaaliqua Ut enim ad minim veniam quis nostrud exercitation ullamcolaboris nisi ut aliquip ex ea commodo consequat Duis aute iruredolor in reprehenderit in voluptatevelit esse cillum dolore eufugiat nulla pariatur Excepteur sint occaecat cupidatat non proidentsunt in culpa qui officia deserunt mollit anim id est laborum Loremipsum dolor sit amet consectetur adipiscing proident estanim sedmollit pariatur do', 
        'anim id est laborum Lorem ipsum dolor sit amet consecteturadipiscing elit sed do eiusmod tempor incididunt ut labore et doloremagna aliqua Ut enim ad minim veniam quis nostrud exercitationullamco laboris nisi ut aliquip ex ea commodo consequat Duis auteirure dolor in reprehenderit in voluptate velit esse cillum doloreeu fugiat nulla pariatur Excepteur sint occaecat cupidatat nonproident sunt in culpa qui officia deserunt mollit elit sit in ametexercitation mollit sint nulla non minim tempor aliqua consequatveniam fugiat dolor sed ullamco',
        'Lorem ipsum dolor sit amet consectetur adipiscing elit sed doeiusmod tempor incididunt ut labore et dolore magna aliqua Ut enimad minim veniam quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur Excepteur sint occaecat cupidatat non proident sunt inculpa qui officia deserunt mollit anim id est laborum amet ea autein occaecat ut nulla nisi irure consectetur quis sint Excepteur euculpa est',
        'veniam quis nostrud exercitation ullamco laboris nisi ut aliquip exea commodo consequat Duis aute irure dolor in reprehenderit involuptate velit esse cillum dolore eu fugiat nulla pariatur Excepteur sint occaecat cupidatat nonproident sunt in culpa quiofficia deserunt mollit anim id est laborum Lorem ipsum dolor sitamet consectetur adipiscing elit sed do eiusmod tempor incididunt utlabore et dolore magna aliqua Ut enim ad minim qui commodo dolorlabore veniam tempor laboris anim cillum',
        'Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollitanim id est laborum Lorem ipsum dolorsit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et doloremagna aliqua Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat eiusmod ametcupidatat deserunt Ut labore minim reprehenderit proident ad Duisdolore ullamco veniam et elit laboris',
        'anim id est laborum Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et doloremagna aliqua Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip exea commodo consequat Duis auteirure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Excepteur sint occaecat cupidatat nonproident sunt in culpa qui officia deserunt mollit nulla eu officia in non quis voluptate dolore dolor exercitation amet eiusmod Utminim sunt',
        'tempor incididunt ut labore et dolore magna aliqua Ut enim ad minimveniam quis nostrud exercitation ullamco laboris nisi ut aliquip exea commodo consequat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum Lorem ipsum dolor sitamet consectetur adipiscing elit sed do eiusmod cillum id tempor commodo nulla sit qui nostrud Excepteur esse proident do in quisveniam velit',
        'ullamco laboris nisi ut aliquip ex ea commodo consequat Duis auteirure dolor in reprehenderit in voluptate velit esse cillum doloreeu fugiat nulla pariatur Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Utenim ad minim veniam quis nostrud exercitation in Excepteur eiusmodest ut ullamco deserunt velit enim ut adipiscing veniam minim do laboris dolore aliqua commodo',
        'magna aliqua Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat Duis auteirure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore Lorem nulla nostrudad id pariatur aliqua do sit ut quis ipsum incididunt ullamco eucillum Excepteur ex proident'
    ];
    const random = Math.floor(Math.random() * sentences.length);
    document.getElementById('lorem-ipsum').innerHTML = sentences[random];
}